# Generated by Django 3.2.7 on 2022-04-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('login_code', models.CharField(max_length=32, verbose_name='验证码')),
                ('user_token', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'table_login',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_token', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_avatar', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'table_user',
            },
        ),
    ]
