# Generated by Django 3.2.7 on 2022-05-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_collection',
            field=models.CharField(default='', max_length=255),
        ),
    ]
