# Generated by Django 3.2.7 on 2022-05-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_user_user_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_collection',
            field=models.CharField(default=-1, max_length=255),
        ),
    ]
